[package]
name = "api-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
clap = { version = "4.5.50", features = ["derive", "env"] }
env_logger = "0.11.8"
once_cell = "1.21.3"
reqwest = "0.12.24"
tokio = "1.48.0"
url = "2.5.7"
